CREATE PROCEDURE `create_index` ()
AS

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Accessories', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_ACCESSORIES where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Artwork', CASE WHEN GENUINE = 'YES' THEN 'GENUINE' ELSE 'FAKE' END, SOURCE, 'NA', BUY, SELL from DODOBAY.SHEETS_ITEMS_ARTWORK where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Bags', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_BAGS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Bottoms', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_BOTTOMS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Ceiling Decor', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_CEILING_DECOR where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Clothing Other', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_CLOTHING_OTHER where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Dress-Up', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_DRESS_UP where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, VARIATION, 'NA', 'Fencing', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_FENCING where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Floors', 'NA', SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_FLOORS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Fossils', 'NA', SOURCE, 'NA', BUY, SELL from DODOBAY.SHEETS_ITEMS_FOSSILS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Gyroids', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_GYROIDS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Headwear', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_HEADWEAR where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Housewares', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_HOUSEWARES where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Interior Structures', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_INTERIOR_STRUCTURES where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Miscellaneous', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_MISCELLANEOUS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, ALBUM_IMAGE, COLOR_1, COLOR_2, 'Music', 'NA', SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_MUSIC where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, INVENTORY_IMAGE, COLOR_1, COLOR_2, 'Other', 'NA', SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_OTHER where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Photos', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_PHOTOS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Posters', 'NA', SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_POSTERS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, 'NA', 'NA', 'Recipes', 'NA', SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_RECIPES where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Rugs', 'NA', SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_RUGS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, 'NA', 'NA', 'NA', 'Seasons and Events', 'NA', 'NA', 'NA', 'NA', 'NA' from DODOBAY.SHEETS_ITEMS_SEASONS_AND_EVENTS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Shoes', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_SHOES where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Socks', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_SOCKS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Tools/Goods', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_TOOLS_GOODS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CLOSET_IMAGE, COLOR_1, COLOR_2, 'Tops', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_TOPS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, STORAGE_IMAGE, COLOR_1, COLOR_2, 'Umbrellas', 'NA', SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_UMBRELLAS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Wall-mounted', VARIATION, SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_WALL_MOUNTED where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, 'Wallpaper', 'NA', SOURCE, SEASON_EVENT, BUY, SELL from DODOBAY.SHEETS_ITEMS_WALLPAPER where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, PHOTO_IMAGE, COLOR_1, COLOR_2, 'Villagers', 'NA', 'NA', 'NA', 'NA', 'NA' from DODOBAY.SHEETS_ITEMS_VILLAGERS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, 'NA', 'NA', 'NA', 'Achievements', 'NA', 'NA', 'NA', 'NA', 'NA' from DODOBAY.SHEETS_ITEMS_ACHIEVEMENTS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, 'NA', 'NA', 'Construction', 'NA', 'NA', 'NA', BUY, 'NA' from DODOBAY.SHEETS_ITEMS_CONSTRUCTION where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CRITTERPEDIA_IMAGE, COLOR_1, COLOR_2, 'Fish', 'NA', 'NA', 'NA', 'NA', SELL from DODOBAY.SHEETS_ITEMS_FISH where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CRITTERPEDIA_IMAGE, COLOR_1, COLOR_2, 'Insects', 'NA', 'NA', 'NA', 'NA', SELL from DODOBAY.SHEETS_ITEMS_INSECTS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, BODY_COLOR, HEAD_COLOR, 'Message Cards', 'NA', 'NA', 'NA', BUY, 'NA' from DODOBAY.SHEETS_ITEMS_MESSAGE_CARDS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, 'NA', 'NA', 'NA', 'Paradise Planning', 'NA', 'NA', 'NA', 'NA', 'NA' from DODOBAY.SHEETS_ITEMS_PARADISE_PLANNING where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, IMAGE, 'NA', 'NA', 'Reactions', 'NA', SOURCE, SEASON_EVENT, 'NA', 'NA' from DODOBAY.SHEETS_ITEMS_REACTIONS where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, CRITTERPEDIA_IMAGE, COLOR_1, COLOR_2, 'Sea Creatures', 'NA', 'NA', 'NA', 'NA', SELL from DODOBAY.SHEETS_ITEMS_SEA_CREATURES where NAME != 'NA';

INSERT INTO DODOBAY.ITEMS(UNIQUE_ENTRY_ID, NAME, IMAGE, COLOR_1, COLOR_2, category_id, VARIATION, SOURCE, SEASON_EVENT, BUY, SELL)
SELECT UNIQUE_ENTRY_ID, NAME, PHOTO_IMAGE, NAME_COLOR, BUBBLE_COLOR, 'Special NPCs', 'NA', 'NA', 'NA', 'NA', 'NA' from DODOBAY.SHEETS_ITEMS_SPECIAL_NPCS where NAME != 'NA';

GO;
